Feature/todo list (#2)
* #1 indention to space 2

* #1 indention and slf4j

* #1 slf4j with logback

* Ref #1 logback format, gradle run and gradle.properties

* Ref #1 configurable license

* Fix #1 readme updated

diff --git a/{{cookiecutter.project_name}}/gradle/config/git/commit-msg b/{{cookiecutter.project_name}}/gradle/config/git/commit-msg
--- a/{{cookiecutter.project_name}}/gradle/config/git/commit-msg
+++ b/{{cookiecutter.project_name}}/gradle/config/git/commit-msg
@@ -5,6 +5,6 @@ commit_regex='([0-9]+|merge)'
 error_msg="Aborting commit. Your commit message is missing either Issue ('#10') or 'Merge'"
 
 if ! grep -iqE "$commit_regex" "$1"; then
-    echo "$error_msg" >&2
-    exit 1
+  echo "$error_msg" >&2
+  exit 1
 fi
diff --git a/{{cookiecutter.project_name}}/gradle/config/git/pre-push b/{{cookiecutter.project_name}}/gradle/config/git/pre-push
--- a/{{cookiecutter.project_name}}/gradle/config/git/pre-push
+++ b/{{cookiecutter.project_name}}/gradle/config/git/pre-push
@@ -3,12 +3,12 @@ CMD="./gradlew check"
 # Check if we actually have commits to push
 commits=`git log @{u}..`
 if [ -z "$commits" ]; then
- exit 0
+  exit 0
 fi
 $CMD
 RESULT=$?
 if [ $RESULT -ne 0 ]; then
- echo "failed $CMD"
- exit 1
+  echo "failed $CMD"
+  exit 1
 fi
 exit 0
